modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/LRRCommunity/boston/issues"

[[mods]]
modId="boston"
version="${file.jarVersion}"
displayName="Punch-A-Chunk"
displayURL="https://github.com/LRRCommunity/boston"
description='''
Adds a tracking webpage to a Forge server at 0.0.0.0:9292.
'''

[[dependencies.boston]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.boston]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"
